version: '3.7'
services:
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    hostname: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=es-twitter-cluster
      - cluster.initial_master_nodes=elastic-1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elastic-cluster/data01_7_17_4:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    command: logstash -f /etc/logstash/conf.d/logback.conf
    ports:
      - "9600:9600"
    depends_on:
      - elastic-1
    volumes:
      - ./config/logback.conf:/etc/logstash/conf.d/logback.conf
      - ./volumes/elastic-cluster/docker-logs/logstash:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      CLUSTER_NAME: es-twitter-cluster
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elastic-1:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}


volumes:
  data01_7_17_4:
    driver: local