version: '3.7'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - 5601:5601
#    depends_on:
#      - elastic-1
#      - elastic-2
#      - elastic-3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    environment:
      ELASTICSEARCH_HOSTS: http://elastic-1:9200
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elastic-1:9200
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      CLUSTER_NAME: es-twitter-cluster
    networks:
      - ${GLOBAL_NETWORK:-elastic}
  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    command: logstash -f /etc/logstash/conf.d/logback.conf
    ports:
      - "9600:9600"
#    depends_on:
#      - elastic-1
#      - elastic-2
#      - elastic-3
    volumes:
      - ./config/logback.conf:/etc/logstash/conf.d/logback.conf
      - ./volumes/elastic-cluster/docker-logs/logstash:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      CLUSTER_NAME: es-twitter-cluster
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elastic-1:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}