version: '3.7'
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - "POSTGRES_USER=keycloak"
      - "POSTGRES_PASSWORD=keycloak"
      - "POSTGRES_DB=keycloak"
    user: root
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./volumes/postgres/config:/etc/postgresql
    networks:
      - ${GLOBAL_NETWORK:-postgres}