version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - 9091:8080
    hostname: keycloak
    environment:
      - "KEYCLOAK_ADMIN=book-hive-test"
      - "KEYCLOAK_ADMIN_PASSWORD=book-hive-test"
      - "KC_DB=oracle"
      - "KC_DB_URL=jdbc:oracle:thin:@oracle:1521:orcl"
      - "KC_DB_URL_PORT=1521"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"
      - "PROXY_ADDRESS_FORWARDING=true"
      - "KC_HTTP_ENABLED=true"
    command: "start-dev "