version: '3'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: my-oracle-db
    environment:
      - ORACLE_PWD=rootjava
      - ORACLE_SID=orcl
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./oradata:/opt/oracle/oradata
    restart: always
