version: '3'
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"  # Splunk Web interface
      - "8088:8088"  # HTTP Event Collector (HEC)
      - "8089:8089"  # Splunk management port
      - "9997:9997"  # Splunk indexing port
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=<admin_password>  # Change this to set your admin password
    volumes:
      - splunk_data:/opt/splunk/var/lib/splunk
      - splunk_etc:/opt/splunk/etc

volumes:
  splunk_data:
  splunk_etc: